#!/bin/bash

GITVER=`wget -qO- https://www.github.com/pineappleEA/Pineapple-Linux-Binary/releases/tag/continuous | grep pineappleEA/Pineapple-Linux-Binary/commit/ | cut -d '"' -f 2 | cut -d '/' -f 5 | awk '!x[$0]++'` 
APPVER=`cat $APPDIR/version.txt`

if [ "$GITVER" = "$APPVER" ]; then
	$APPDIR/usr/bin/yuzu
else
	$APPDIR/update.sh
fi
